name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/hdl/debian-buster/impl:prjtrellis
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: 'arty'
            args: ''
          - board: 'trellisboard'
            args: ''
          - board: 'ecpix5'
            args: ''
          - board: 'de10nano'
    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install Tools
      - name: Install Tools
        run: |
          apt-get -qy update
          apt-get -qy install wget build-essential python3 python3-pip verilator libevent-dev libjson-c-dev \
            device-tree-compiler python3-requests python3-pexpect

      # Install (n)Migen / LiteX / Cores
      - name: Install LiteX
        run: |
          wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
          python3 litex_setup.py init install

      # Install RISC-V GCC
      - name: Install RISC-V GCC
        run: |
          python3 litex_setup.py gcc

      # Test
      - name: Build SoC
        run: |
          export PATH=$PATH:~/.local/bin
          export PATH=$PATH:$(realpath ../riscv64-*/bin)
          git clean -dfx
          ./make.py --board=${{ matrix.board }} ${{ matrix.args }}
          git status

      # Upload
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.board }}
          path: build/*/gateware
